sudo: false
language: python
install:
- pip install mkdocs
- pip install mkdocs-material
script:
- git clean -f -d -x
after_success:
- git config user.name $GITHUB_USERNAME
- git config user.email $GITHUB_EMAIL
- git remote add gh-token "https://${GH_TOKEN}@github.com/cruizba/Bike3S-documentation.git";
- git fetch gh-token && git fetch gh-token gh-pages:gh-pages;
- mkdocs gh-deploy -v --clean --remote-name gh-token;
branches:
  only:
  - master