site_name: Bike3S - Documentation
theme: material
pages:
  - Introduction: index.md
  - Users Guide: users_guide.md
  - Developers Guide: developers_guide.md
  - Papers: papers.md
markdown_extensions:
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_png
